title: Synoptix Docs
description: Documentation for Synoptix's platforms and products
theme: just-the-docs

url: https://docs.synoptix.co.uk

aux_links:
  Synoptix Home: www.synoptix.co.uk 

nav_external_links:
- title: Synx-Assure
  url: https://docs.synoptix.co.uk/assurance
  hide_icon: false # set to true to hide the external link icon - defaults to false
  opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false
- title: Synx-Recon
  url: https://docs.synoptix.co.uk/synx-recon
  hide_icon: false # set to true to hide the external link icon - defaults to false
  opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false


search_enabled: false

logo: "/assets/site_assets/images/SynoptixBlue_01.png"
favicon_ico: "/assets/site_assets/images/SBlue_01.png"

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red